### ISSUE TITLE
Register An Account

### ISSUE THREAD

**Issue by Conal2023** [Conal2023/LoveFlowers1.1#3]
As a **Site User**, I want an easy registration process to create a personal account. This account should grant me access to additional features such as viewing my order history, order confirmations, and saved payment information

**Acceptance Criteria**

1. Users should be able to locate the "My Account" icon in the top right corner. Clicking on this icon should open a dropdown menu.
2. Unauthenticated users should see a "Register" option in the dropdown menu. Clicking on this option should redirect them to the registration page.
3. After successfully registering, users should receive a prompt on the page confirming their successful registration.

**Tasks**

- [x] Include the "Register" option in the dropdown menu of the Account icon.

- [x] Configure the Allauth library to manage user authentication, registration, and confirmation email sending.

- [x] Implement a success message to inform users that a confirmation email has been sent.
