### ISSUE TITLE
View Items In Bag To Be Purchased

### ISSUE THREAD

**Issue by Conal2023** [Conal2023/LoveFlowers1.1#6]
As a **Shopper**, I want to be able to **view the items in my cart/bag before purchase** so that I can review the total cost of my purchase and ensure I am receiving all the items I intend to purchase.

**Acceptance Criteria**

1. Users should be directed to the bag page upon clicking the cart icon in the upper right corner.
   
**Tasks**

- [x] Develop a bag app.

- [x] Create the `view_bag` view within `views.py` in the bag app.

- [x] Design a bag template and apply customized styling.
